R CMD check (still some errors); devtools::test() (some errors); R CMD INSTALL (success :tada:)
```
==> devtools::check(args = c('--as-cran'))

══ Documenting ═══════════════════════════════════════════════════════════════════════
ℹ Updating sobir documentation
ℹ Loading sobir
Warning: Objects listed as exports, but not present in namespace:
• NR_perm_area
• NR_perm_plot
Warning: [perm_area.R:20] @examples requires a value
Writing NAMESPACE
Writing perm_area.Rd
Writing perm_plot.Rd
Deleting NR_perm_area.Rd and NR_perm_plot.Rd

══ Building ══════════════════════════════════════════════════════════════════════════
Setting env vars:
• CFLAGS    : -Wall -pedantic -fdiagnostics-color=always
• CXXFLAGS  : -Wall -pedantic -fdiagnostics-color=always
• CXX11FLAGS: -Wall -pedantic -fdiagnostics-color=always
• CXX14FLAGS: -Wall -pedantic -fdiagnostics-color=always
• CXX17FLAGS: -Wall -pedantic -fdiagnostics-color=always
• CXX20FLAGS: -Wall -pedantic -fdiagnostics-color=always
── R CMD build ───────────────────────────────────────────────────────────────────────
✔  checking for file 'C:\Users\RuanvanMazijk\sobir/DESCRIPTION' (380ms)
─  preparing 'sobir': (435ms)
✔  checking DESCRIPTION meta-information ...
─  installing the package to build vignettes
E  creating vignettes (1m 7.4s)
   --- re-building 'sobir-getstarted.Rmd' using rmarkdown
   Quitting from lines 209-219 (sobir-getstarted.Rmd) 
   Error: processing vignette 'sobir-getstarted.Rmd' failed with diagnostics:
   missing value where TRUE/FALSE needed
   --- failed re-building 'sobir-getstarted.Rmd'
   
   SUMMARY: processing the following file failed:
     'sobir-getstarted.Rmd'
   
   Error: Vignette re-building failed.
   Execution halted
Error in `(function (command = NULL, args = character(), error_on_status = TRUE, …`:
! System command 'Rcmd.exe' failed
---
Exit status: 1
stdout & stderr: <printed>
---
Backtrace:
 1. devtools::check(args = c("--as-cran"), check_dir = dirname(getwd()))
 2. withr::with_envvar(pkgbuild::compiler_flags(FALSE), action = "prefix", …
 3. base::force(code)
 4. pkgbuild::build(pkg$path, tempdir(), args = build_args, quiet = quiet, …
 5. withr::with_temp_libpaths(rcmd_build_tools(options$cmd, c(options$path, …
 6. base::force(code)
 7. pkgbuild::rcmd_build_tools(options$cmd, c(options$path, options$args), …
 8. pkgbuild::with_build_tools({ …
 9. withr::with_path(rtools_path(), code)
10. base::force(code)
11. base::withCallingHandlers(callr::rcmd_safe(..., env = env, spinner = FALSE, …
12. callr::rcmd_safe(..., env = env, spinner = FALSE, show = FALSE, …
13. callr:::run_r(options)
14. base::with(options, with_envvar(env, do.call(processx::run, c(list(bin, …
15. base::with.default(options, with_envvar(env, do.call(processx::run, …
16. base::eval(substitute(expr), data, enclos = parent.frame())
17. base::eval(substitute(expr), data, enclos = parent.frame())
18. callr:::with_envvar(env, do.call(processx::run, c(list(bin, args = real_cmdargs, …
19. base::force(code)
20. base::do.call(processx::run, c(list(bin, args = real_cmdargs, stdout_line_callback = r…
21. (function (command = NULL, args = character(), error_on_status = TRUE, …
22. base::throw(new_process_error(res, call = sys.call(), echo = echo, …
23. | base::signalCondition(cond)
24. (function (e) …
25. asNamespace("callr")$err$throw(e)
Execution halted

Exited with status 1.
```

```
==> devtools::test()

ℹ Testing sobir
✔ | F W S  OK | Context
✔ |         1 | extract_bpts [0.2s]                                                   
✔ |         1 | bpts_plot [0.3s]                                                      
✔ |   2     2 | calc_area [1.0s]                                                      
──────────────────────────────────────────────────────────────────────────────────────
Warning (tests.R:29): calc_area should return a list of the three no-data zone areas unsing two vectors
collapsing to unique 'x' values
Backtrace:
 1. sobir::calc_area(a, b)
      at tests.R:29:2
 2. DescTools::AUC(topr_crnr$x, topr_crnr$y, absolutearea = TRUE)
      at sobir/R/calc_area.R:67:2
 3. stats::approx(...)
 4. stats:::regularize.values(x, y, ties, missing(ties), na.rm = na.rm)

Warning (tests.R:29): calc_area should return a list of the three no-data zone areas unsing two vectors
collapsing to unique 'x' values
Backtrace:
 1. sobir::calc_area(a, b)
      at tests.R:29:2
 2. DescTools::AUC(topl_crnr$x, topl_crnr$y, absolutearea = TRUE)
      at sobir/R/calc_area.R:71:2
 3. stats::approx(...)
 4. stats:::regularize.values(x, y, ties, missing(ties), na.rm = na.rm)
──────────────────────────────────────────────────────────────────────────────────────
✖ | 1       1 | perm_area [2.6s]                                                      
──────────────────────────────────────────────────────────────────────────────────────
Failure (tests.R:41): perm_area should calculate the no-data zone areas for each permutation of the data simulated nsim times
bperm$data[6, 4] is not strictly less than 0.6. Difference: 17.4
──────────────────────────────────────────────────────────────────────────────────────
✖ | 1       1 | perm_plot [2.4s]                                                      
──────────────────────────────────────────────────────────────────────────────────────
Failure (tests.R:53): perm_plot should pull the appropriate data from the perm_area analysis
bpplot$data[5, 4] is not strictly less than 0.7. Difference: 16.3
──────────────────────────────────────────────────────────────────────────────────────

══ Results ═══════════════════════════════════════════════════════════════════════════
Duration: 8.1 s

[ FAIL 2 | WARN 2 | SKIP 0 | PASS 6 ]
```