R CMD check; devtools::test() (no effects); R CMD INSTALL (from MBA)
```
==> devtools::check(args = c('--as-cran'))

══ Documenting ════════════════════════════════════════════════════════════
ℹ Updating sobir documentation
ℹ Loading sobir

══ Building ═══════════════════════════════════════════════════════════════
Setting env vars:
• CFLAGS    : -Wall -pedantic -fdiagnostics-color=always
• CXXFLAGS  : -Wall -pedantic -fdiagnostics-color=always
• CXX11FLAGS: -Wall -pedantic -fdiagnostics-color=always
• CXX14FLAGS: -Wall -pedantic -fdiagnostics-color=always
• CXX17FLAGS: -Wall -pedantic -fdiagnostics-color=always
• CXX20FLAGS: -Wall -pedantic -fdiagnostics-color=always
✔  checking for file ‘/Users/ruanvanmazijk/sobir/DESCRIPTION’ ...
─  preparing ‘sobir’:
✔  checking DESCRIPTION meta-information ...
─  installing the package to build vignettes
✔  creating vignettes (44.7s)
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘sobir_0.1.2.tar.gz’
   
══ Checking ═══════════════════════════════════════════════════════════════
Setting env vars:
• _R_CHECK_CRAN_INCOMING_REMOTE_               : FALSE
• _R_CHECK_CRAN_INCOMING_                      : FALSE
• _R_CHECK_FORCE_SUGGESTS_                     : FALSE
• _R_CHECK_PACKAGES_USED_IGNORE_UNUSED_IMPORTS_: FALSE
• NOT_CRAN                                     : true
── R CMD check ────────────────────────────────────────────────────────────
─  using log directory ‘/Users/ruanvanmazijk/sobir.Rcheck’
─  using R version 4.2.1 (2022-06-23)
─  using platform: aarch64-apple-darwin20 (64-bit)
─  using session charset: UTF-8
─  using options ‘--no-manual --as-cran’
✔  checking for file ‘sobir/DESCRIPTION’
─  checking extension type ... Package
─  this is package ‘sobir’ version ‘0.1.2’
─  package encoding: UTF-8
✔  checking package namespace information
✔  checking package dependencies (6.5s)
✔  checking if this is a source package ...
✔  checking if there is a namespace
✔  checking for executable files ...
✔  checking for hidden files and directories
✔  checking for portable file names ...
✔  checking for sufficient/correct file permissions
✔  checking whether package ‘sobir’ can be installed (3.7s)
✔  checking installed package size ...
✔  checking package directory ...
✔  checking for future file timestamps (676ms)
✔  checking ‘build’ directory
✔  checking DESCRIPTION meta-information ...
✔  checking top-level files ...
✔  checking for left-over files
✔  checking index information ...
✔  checking package subdirectories ...
✔  checking R files for non-ASCII characters ...
✔  checking R files for syntax errors ...
✔  checking whether the package can be loaded (932ms)
✔  checking whether the package can be loaded with stated dependencies (902ms)
✔  checking whether the package can be unloaded cleanly (981ms)
✔  checking whether the namespace can be loaded with stated dependencies (902ms)
✔  checking whether the namespace can be unloaded cleanly (916ms)
✔  checking loading without being on the library search path (947ms)
N  checking dependencies in R code (930ms)
   Namespaces in Imports field not imported from:
     ‘devtools’ ‘raster’ ‘rlang’ ‘sp’ ‘usethis’
     All declared Imports should be used.
✔  checking S3 generic/method consistency (1.3s)
✔  checking replacement functions (890ms)
✔  checking foreign function calls (921ms)
✔  checking R code for possible problems (5.2s)
✔  checking Rd files ...
✔  checking Rd metadata ...
✔  checking Rd line widths ...
✔  checking Rd cross-references ...
✔  checking for missing documentation entries (893ms)
✔  checking for code/documentation mismatches (2.8s)
✔  checking Rd \usage sections (1.4s)
✔  checking Rd contents ...
✔  checking for unstated dependencies in examples ...
✔  checking contents of ‘data’ directory ...
✔  checking data for non-ASCII characters ...
✔  checking LazyData
✔  checking data for ASCII and uncompressed saves ...
✔  checking installed files from ‘inst/doc’ ...
✔  checking files in ‘vignettes’ ...
✔  checking examples (2.9s)
✔  checking for unstated dependencies in ‘tests’ ...
─  checking tests ...
─  Running ‘testthat.R’ (2s)
E  Some test files failed
   Running the tests in ‘tests/testthat.R’ failed.
   Last 13 lines of output:
      1. sobir::calc_area(a, b)
           at tests.R:29:2
      2. DescTools::AUC(topl_crnr$x, topl_crnr$y, absolutearea = TRUE)
      3. stats::approx(...)
      4. stats:::regularize.values(x, y, ties, missing(ties), na.rm = na.rm)
     
     ══ Failed tests ════════════════════════════════════════════════════════════════
     ── Failure ('tests.R:42'): perm_area should calculate the no-data zone areas for each permutation of the data simulated nsim times ──
     bperm$data[6, 4] is not strictly more than 0.5. Difference: -0.473
     ── Failure ('tests.R:54'): perm_plot should pull the appropriate data from the perm_area analysis ──
     bpplot$data[5, 4] is not strictly more than 0.6. Difference: -0.376
     
     [ FAIL 2 | WARN 2 | SKIP 0 | PASS 6 ]
     Error: Test failures
     Execution halted
✔  checking for unstated dependencies in vignettes ...
✔  checking package vignettes in ‘inst/doc’ ...
✔  checking re-building of vignette outputs (30.3s)
✔  checking for non-standard things in the check directory
✔  checking for detritus in the temp directory
   
   See
     ‘/Users/ruanvanmazijk/sobir.Rcheck/00check.log’
   for details.
   
   
── R CMD check results ─────────────────────────────────── sobir 0.1.2 ────
Duration: 1m 8.6s

❯ checking tests ...
  See below...

❯ checking dependencies in R code ... NOTE
  Namespaces in Imports field not imported from:
    ‘devtools’ ‘raster’ ‘rlang’ ‘sp’ ‘usethis’
    All declared Imports should be used.

── Test failures ──────────────────────────────────────────── testthat ────

> library(testthat)
> library(sobir)
> 
> test_check("sobir")
[ FAIL 2 | WARN 2 | SKIP 0 | PASS 6 ]

══ Warnings ════════════════════════════════════════════════════════════════════
── Warning ('tests.R:29'): calc_area should return a list of the three no-data zone areas unsing two vectors ──
collapsing to unique 'x' values
Backtrace:
 1. sobir::calc_area(a, b)
      at tests.R:29:2
 2. DescTools::AUC(topr_crnr$x, topr_crnr$y, absolutearea = TRUE)
 3. stats::approx(...)
 4. stats:::regularize.values(x, y, ties, missing(ties), na.rm = na.rm)
── Warning ('tests.R:29'): calc_area should return a list of the three no-data zone areas unsing two vectors ──
collapsing to unique 'x' values
Backtrace:
 1. sobir::calc_area(a, b)
      at tests.R:29:2
 2. DescTools::AUC(topl_crnr$x, topl_crnr$y, absolutearea = TRUE)
 3. stats::approx(...)
 4. stats:::regularize.values(x, y, ties, missing(ties), na.rm = na.rm)

══ Failed tests ════════════════════════════════════════════════════════════════
── Failure ('tests.R:42'): perm_area should calculate the no-data zone areas for each permutation of the data simulated nsim times ──
bperm$data[6, 4] is not strictly more than 0.5. Difference: -0.473
── Failure ('tests.R:54'): perm_plot should pull the appropriate data from the perm_area analysis ──
bpplot$data[5, 4] is not strictly more than 0.6. Difference: -0.376

[ FAIL 2 | WARN 2 | SKIP 0 | PASS 6 ]
Error: Test failures
Execution halted

1 error ✖ | 0 warnings ✔ | 1 note ✖
Error: R CMD check found ERRORs
Execution halted

Exited with status 1.
```

```
==> devtools::test()

ℹ Testing sobir
✔ | F W S  OK | Context
✔ |         1 | extract_bpts                                               
✔ |         1 | bpts_plot [0.2s]                                           
✔ |   2     2 | calc_area [0.1s]                                           
───────────────────────────────────────────────────────────────────────────
Warning (tests.R:29): calc_area should return a list of the three no-data zone areas unsing two vectors
collapsing to unique 'x' values
Backtrace:
 1. sobir::calc_area(a, b)
      at tests.R:29:2
 2. DescTools::AUC(topr_crnr$x, topr_crnr$y, absolutearea = TRUE)
      at sobir/R/calc_area.R:67:2
 3. stats::approx(...)
 4. stats:::regularize.values(x, y, ties, missing(ties), na.rm = na.rm)

Warning (tests.R:29): calc_area should return a list of the three no-data zone areas unsing two vectors
collapsing to unique 'x' values
Backtrace:
 1. sobir::calc_area(a, b)
      at tests.R:29:2
 2. DescTools::AUC(topl_crnr$x, topl_crnr$y, absolutearea = TRUE)
      at sobir/R/calc_area.R:71:2
 3. stats::approx(...)
 4. stats:::regularize.values(x, y, ties, missing(ties), na.rm = na.rm)
───────────────────────────────────────────────────────────────────────────
✖ | 1       1 | perm_area [0.5s]                                           
───────────────────────────────────────────────────────────────────────────
Failure (tests.R:42): perm_area should calculate the no-data zone areas for each permutation of the data simulated nsim times
bperm$data[6, 4] is not strictly more than 0.5. Difference: -0.473
───────────────────────────────────────────────────────────────────────────
✖ | 1       1 | perm_plot [0.5s]                                           
───────────────────────────────────────────────────────────────────────────
Failure (tests.R:54): perm_plot should pull the appropriate data from the perm_area analysis
bpplot$data[5, 4] is not strictly more than 0.6. Difference: -0.376
───────────────────────────────────────────────────────────────────────────

══ Results ════════════════════════════════════════════════════════════════
Duration: 1.4 s

[ FAIL 2 | WARN 2 | SKIP 0 | PASS 6 ]
```

```
==> R CMD INSTALL --preclean --no-multiarch --with-keep.source sobir

* installing to library ‘/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library’
* installing *source* package ‘sobir’ ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (sobir)
```